apiVersion: v2
name: kubectyl
home: https://kubectyl.org
description: Put your servers on autopilot with Kubernetes implementation and get rid of Pterodactyl nodes.
sources:
  - https://github.com/kubectyl/panel
  - https://github.com/kubectyl/kuber
maintainers:
  - name: andrei0465
    email: andrei.mociu@kubectyl.org
  - name: raefon
    email: raefon@users.noreply.github.com
keywords:
  - kubectyl
  - panel
  - kuber
  - kubernetes
type: application
version: 0.2.5 # Bumped version
appVersion: "0.1.0"
dependencies:
  - name: mariadb
    version: "24.0.2" # Updated for MariaDB 11.8+
    repository: file://charts/mariadb
  - name: redis
    version: "24.1.0" # Updated for Redis 8.x
    repository: file://charts/redis