---
apiVersion: v2
name: common
description: Function library for kdlhost helm charts
type: library
version: 0.2.5
keywords:
  - kdlhost-charts
  - common
home: https://raefon.github.io/kdlhost-charts/common
maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Add rendering for prometheus servicemonitor addon in common template
