{{- if and .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.configlocal.name }}"
  namespace: {{ .Release.Namespace }}
{{- with .Values.configlocal.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "tenet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.configlocal.additionalLabels }}
    {{ toYaml .Values.configlocal.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.configlocal.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.configlocal.size | quote }}
  storageClassName: "{{ .Values.configlocal.storageClass }}"
{{- end }}