---
apiVersion: v2
name: nut-exporter
description: Prometheus Exporter for NUT (Network UPS Tools)
type: application
version: 0.1.2
appVersion: "latest"
icon: ""
sources:
  - https://github.com/druggeri/nut_exporter

keywords:
  - ups
  - nut
  - exporter
  - prometheus

dependencies:
  - name: common
    version: ~0.2.0
    repository: https://raefon.github.io/kdlhost-charts/

maintainers:
  - name: raefon
    email: raefon@users.noreply.github.com 

annotations:
  artifacthub.io/changes: |
    - Update port configuration to match nut-exporter defaults.
  artifacthub.io/images: |
    - druggeri/nut_exporter:latest
